import React, { useState } from "react";
import './../css/Experience.css';
import './../css/Topic.css';
import './../App.css';
import SkyLabsLogo from './../assets/skylabs_logo.png';
import SetronicaLogo from './../assets/setronica_logo.png';
import TridensLogo from '../assets/Tridens.png';

const experiences = [
    {
        company: "Tridens d.o.o",
        role: "Software Developer",
        timeframe: "March 24 2025 - Current",
        logo: TridensLogo,
        description: `At Tridens d.o.o, I have been working as a Java developer, contributing to the integration and development of
        backend systems. My responsibilities include collaborating on the design and implementation of microservices,
        supporting RPC communication, and maintaining high-quality, reliable code through testing and continuous
        improvement.`
    },
    {
        company: "Setronica d.o.o",
        role: "Internship – QA Engineer",
        timeframe: "August 1 2024 - June 1 2025",
        logo: SetronicaLogo,
        description: `At Setronica, I was responsible for the quality assurance of LLM models. My role involved
        thoroughly reviewing the output material generated by these models, assessing the accuracy of
        their solutions, and labeling them as either acceptable or in need of improvement. In addition
        to grading the outputs, I provided detailed comments that highlighted specific inaccuracies and
        offered constructive feedback to help improve the model’s performance.`
    },
    {
        company: "Skylabs d.o.o",
        role: "Internship – Software Engineer",
        timeframe: "August 1 2023 - 31 September 2023",
        logo: SkyLabsLogo,
        description: `At Skylabs d.o.o, I was responsible for transforming C++ libraries into Python-compatible
        modules by creating wrappers. Additionally, I developed a RESTful API to provide easy access to
        these libraries. My role involved the entire development lifecycle, from concept to deployment.
        these libraries. My role involved the entire development lifecycle, from concept to deployment.
        Through this experience, I enhanced my skills in C++, Python, web development, and project
        management, gaining valuable expertise in software integration and API design.`
    }
];

function Experience() {
    const [currentIndex, setCurrentIndex] = useState(0);

    const handlePrev = () => {
        setCurrentIndex((prevIndex) =>
            prevIndex === 0 ? experiences.length - 1 : prevIndex - 1
        );
    };

    const handleNext = () => {
        setCurrentIndex((prevIndex) =>
            prevIndex === experiences.length - 1 ? 0 : prevIndex + 1
        );
    };

    const currentExp = experiences[currentIndex];

    return (
        <div className="experience-section">
            <div className="topic-box-title">
                <h1 className="topic-card-title">Work Experience</h1>
                <h2 className="subtitle">COMPANIES I WORKED AT</h2>
            </div>
            <div className="carousel-container">
                <button className="carousel-button" onClick={handlePrev}>◀</button>
                <div className="company active">
                    <h1 className="text">{currentExp.company} - {currentExp.role}</h1>
                    <h1 className="timeframe">{currentExp.timeframe}</h1>
                    <hr />
                    <img className="company-logo" src={currentExp.logo} alt={`${currentExp.company} Logo`} />
                    <p className="text">{currentExp.description}</p>
                </div>
                <button className="carousel-button" onClick={handleNext}>▶</button>
            </div>
        </div>
    );
}

export default Experience;
